[project]
name = 'cns'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.cns-generic-stx-manager]
path = 'contracts/cns-generic-stx-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.cns-name]
path = 'contracts/cns-name.clar'
clarity_version = 2
epoch = 2.5

[contracts.cns-root-manager]
path = 'contracts/cns-root-manager.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
